alphasocbeat:
  registry_file: checkpoint.yaml
  api_url: https://api.alphasoc.net
  api_key: <api_key>

setup.dashboards.enabled: true
processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
