version: 2.1
jobs:
  test:
      working_directory: /go/src/github.com/alphasoc/alphasocbeat
      docker:
        - image: circleci/golang:1.16
      steps:
        - checkout
        - run:
            name: Run tests
            command: go test -race -v ./...
  
  build:
    docker:
      - image: circleci/golang:1.16
    working_directory: /go/src/github.com/alphasoc/alphasocbeat
    steps:
      - checkout
      - run:
          name: build
          command: |
            GOARCH=amd64 GOOS=linux   go build -o /tmp/bin/alphasocbeat-linux-amd64
            GOARCH=amd64 GOOS=windows go build -o /tmp/bin/alphasocbeat-windows-amd64.exe
            GOARCH=amd64 GOOS=darwin  go build -o /tmp/bin/alphasocbeat-darwin-amd64
      - persist_to_workspace:
          root: /tmp
          paths:
            - bin
  
  publish:
    docker:
      - image: circleci/golang:1.16
    working_directory: /go/src/github.com/alphasoc/alphasocbeat
    steps:
      - attach_workspace:
          at: .
      - run:
          name: publish
          command: |
            go get github.com/aktau/github-release
            github-release release --draft --user alphasoc --repo alphasocbeat --tag $CIRCLE_TAG
            github-release upload --user alphasoc --repo alphasocbeat --tag $CIRCLE_TAG --name alphasocbeat-linux-amd64       --file bin/alphasocbeat-linux-amd64
            github-release upload --user alphasoc --repo alphasocbeat --tag $CIRCLE_TAG --name alphasocbeat-windows-amd64.exe --file bin/alphasocbeat-windows-amd64.exe
            github-release upload --user alphasoc --repo alphasocbeat --tag $CIRCLE_TAG --name alphasocbeat-darwin-amd64      --file bin/alphasocbeat-darwin-amd64

workflows:
  version: 2
  release:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          requires: 
            - test
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/
      - publish:
          context: github-alphasoc-deploy
          requires:
            - test
            - build
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/