version: 2.1
jobs:
  test:
      working_directory: /go/src/github.com/alphasoc/alphasocbeat
      docker:
        - image: circleci/golang:1.16
      steps:
        - checkout
        - run:
            name: Run tests
            command: go test -race -v ./...

workflows:
  version: 2
  release:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/