version: 2.1
jobs:
  test:
      working_directory: /go/src/github.com/alphasoc/alphasocbeat
      docker:
        - image: circleci/golang:1.16
      steps:
        - checkout
        - run:
            name: Run tests
            command: go test -race -v ./...
  
  build:
    docker:
      - image: circleci/golang:1.16
    working_directory: /go/src/github.com/alphasoc/alphasocbeat
    steps:
      - checkout
      - run:
          name: build
          command: |
            GOARCH=amd64 GOOS=linux   go build -o alphasocbeat-linux-amd64
            GOARCH=amd64 GOOS=windows go build -o alphasocbeat-windows-amd64.exe
            GOARCH=amd64 GOOS=darwin  go build -o alphasocbeat-darwin-amd64
      - run:
          name: make packages
          command: |
            mkdir -p kibana/7/dashboard && cp _meta/kibana.generated/7/dashboard/Alphasocbeat-dashboards.json kibana/7/dashboard/Alphasocbeat-dashboards.json
            tar -cvzf alphasocbeat-linux-amd64.tar.gz alphasocbeat-linux-amd64 alphasocbeat.yml kibana/
            zip alphasocbeat-windows-amd64.zip alphasocbeat-windows-amd64.exe alphasocbeat.yml kibana/7/dashboard/Alphasocbeat-dashboards.json
            tar -cvzf alphasocbeat-darwin-amd64.tar.gz alphasocbeat-darwin-amd64 alphasocbeat.yml kibana/
      - persist_to_workspace:
          root: .
          paths:
            - alphasocbeat-linux-amd64.tar.gz
            - alphasocbeat-windows-amd64.zip
            - alphasocbeat-darwin-amd64.tar.gz
  
  publish:
    docker:
      - image: circleci/golang:1.16
    working_directory: /go/src/github.com/alphasoc/alphasocbeat
    steps:
      - attach_workspace:
          at: .
      - run:
          name: publish
          command: |
            go get github.com/aktau/github-release
            github-release release --draft --user alphasoc --repo alphasocbeat --tag $CIRCLE_TAG
            github-release upload --user alphasoc --repo alphasocbeat --tag $CIRCLE_TAG --name alphasocbeat-linux-amd64.tar.gz  --file alphasocbeat-linux-amd64.tar.gz
            github-release upload --user alphasoc --repo alphasocbeat --tag $CIRCLE_TAG --name alphasocbeat-windows-amd64.zip   --file alphasocbeat-windows-amd64.zip
            github-release upload --user alphasoc --repo alphasocbeat --tag $CIRCLE_TAG --name alphasocbeat-darwin-amd64.tar.gz --file alphasocbeat-darwin-amd64.tar.gz

workflows:
  version: 2
  release:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          requires: 
            - test
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/
      - publish:
          context: github-alphasoc-deploy
          requires:
            - test
            - build
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/